Fix startup error in csvimport.py
As described in
http://stackoverflow.com/questions/11999416/python-argparse-metavar-and-action-store-true-together

metavar and action='store_true' make no sense together, and cause an
exception:

pynYNAB CSV import
Traceback (most recent call last):
  File "./virtualenv/src/nynabapi-abesto/pynYNAB/scripts/csvimport.py", line 165, in <module>
    csvimport_main()
  File "./virtualenv/src/nynabapi-abesto/pynYNAB/scripts/csvimport.py", line 29, in csvimport_main
    help='Forces the import even if a duplicate (same date, account, amount, memo, payee) is found')
  File "/Users/abesto/playground/otp2ynab/virtualenv/lib/python2.7/site-packages/configargparse.py", line 735, in add_argument
    action = self.original_add_argument_method(*args, **kwargs)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1294, in add_argument
    action = action_class(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'metavar'